name: Docker Build Verify

on:
  pull_request:
    branches: [ "master" ]

jobs:
  master:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build dreamer-node
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./node/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/dreamer-node:master
    
    - name: Build dreamer-hasura
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./hasura/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/dreamer-hasura:master