name: Docker Image Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  master:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push dreamer-node
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./node/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/dreamer-node:master
        push: true
    
    - name: Build and push dreamer-hasura
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./hasura/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/dreamer-hasura:master
        push: true
  
  latest:
    runs-on: ubuntu-latest
    needs: master
    environment: Production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push dreamer-node
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./node/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/dreamer-node:latest
        push: true
    
    - name: Build and push dreamer-hasura
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./hasura/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/dreamer-hasura:latest
        push: true
